### ISSUE TITLE
Bypass GNOME's "no expiration" design decision

### ISSUE THREAD

**Issue by PhrozenByte** [vlevit/notify-send.sh#10]
GNOME made the (pretty weird) "design decision" to always ignore the expire time of notifications and even making all notifications persistent (the latter since the introduction of GNOME's notification center). Most applications bypass this behaviour by manually closing notifications after some individual timeouts (yes, instead of unifying expiration times, GNOME made it worse).

It would be great if `notify-send.sh` could easily bypass this behaviour, too. I wrote a simple wrapper script, even though implementing this into `notify-send.sh`'s base script would obviously be simpler and a better approach:

```bash
#!/bin/bash
EXPIRE_TIME=-1
PRINT_ID=

NOTIFY_ARGS=()
while (( $# > 0 )); do
    case "$1" in
        -t|--expire-time|--expire-time=*)
            [[ "$1" = --expire-time=* ]] \
                && EXPIRE_TIME="${1#*=}" \
                || { shift; EXPIRE_TIME="$1"; }
            NOTIFY_ARGS+=( --expire-time "$EXPIRE_TIME" )
            ;;

        -p|--print-id)
            PRINT_ID=yes
            NOTIFY_ARGS+=( --print-id )
            ;;

        *)
            NOTIFY_ARGS+=( "$1" )
            ;;
    esac
    shift
done

NOTIFY_SEND="$(dirname "${BASH_SOURCE[0]}")/notify-send.sh"
if (( "$EXPIRE_TIME" != -1 )); then
    NOTIFICATION_ID="$("$NOTIFY_SEND" --print-id "${NOTIFY_ARGS[@]}")"
    NOTIFY_RC=$?

    if [[ -n "$PRINT_ID" ]]; then
        echo "$NOTIFICATION_ID"
    fi

    if (( "$EXPIRE_TIME" > 0 )); then
        SLEEP_TIME="$(bc <<< "scale=3; $EXPIRE_TIME / 1000")"
        ( sleep "$SLEEP_TIME" ; "$NOTIFY_SEND" --close "$NOTIFICATION_ID" ) &
    else
        "$NOTIFY_SEND" --close "$NOTIFICATION_ID"
    fi

    exit $NOTIFY_RC
fi

"$NOTIFY_SEND" "${NOTIFY_ARGS[@]}"
exit $?
```

**Comment by vlevit** [comment]
@PhrozenByte Sorry for very late reply. If this script is reworked to a PR implementing the timeout workaround as a separate flag I would consider merging it.
