### ISSUE TITLE
-o and -d options not working

### ISSUE THREAD

**Issue by adwait-thattey** [vlevit/notify-send.sh#12]
For me, when using options -o or -d (and even their long versions) it shows 
> Unknown option -o

System: Manjaro Linux
Desktop: KDE Plasma 5

Installed from AUR

**Comment by vlevit** [comment]
@adwait-thattey It's because I haven't careated a new release after -o was added. I'll try to release it soon and publish in AUR. Meanwhile you can use the latest version from git.

**Comment by adwait-thattey** [comment]
Thanks. Will use from git
