### ISSUE TITLE
-o action only works during initial display timout, not from notification history

### ISSUE THREAD

**Issue by bkw777** [vlevit/notify-send.sh#13]
Is there any way to make the action buttons keep working after the notification has timed out and gone to the notification daemon's history?

Example, my desktop default notification timeout is set to only 3 seconds. (lxqt-notificationd in my case). Notifications only appear briefly, then stack up in a history I can pull up when I want.

Now take this command:
`notify-send.sh -o eyes:xeyes "" ""`

If I press the "eyes" button during that first 3 seconds, it works.

If I allow the notification to expire, and then pop it back up from the history, the "eyes" button is still there and still clickable, but has no effect.

I see that during the initial display time there are two notify-action.sh processes that exist in the background while the notification is visible the first time. Once it times out, both of those disappear. When I pull the notification back up from the history, the bg processes do not reappear with it, so that surely explains why the button no longer functions.

Is there a way to make it so the monitor process doesn't go away until the user actively does something with the notification?

In my case, I'm trying to use this from within https://github.com/bkw777/mainline
In that context, it would be ok to have a single notification that gets refreshed or replaced rather than a stack of individual notifications. So maybe there is some way to rig this up using -p or -r or -R or something?

Otherwise, the best I can think of right now is I can override the timeout by using the -t option to specify a very long timeout, and maybe add the -f option, so that the notification never goes to the history, it's either visible and working, or totally gone.

**Comment by vlevit** [comment]
My guess is that lxqt-notificationd might be emitting NotificationClosed signal when it puts a notification to the history. You can check that by running

    gdbus monitor --session --dest org.freedesktop.Notifications --object-path /org/freedesktop/Notifications

and watching the output when notification is about to be moved to the history. If my guess is correct you might see a similar line in standard output 

    /org/freedesktop/Notifications: org.freedesktop.Notifications.NotificationClosed (uint32 7, uint32 1)

The last argument (uint32 1) means notification has expired. Possible reasons from the spec are

> 1 - The notification expired.    
> 2 - The notification was dismissed by the user.
> 3 - The notification was closed by a call to  CloseNotification.
> 4 - Undefined/reserved reasons.

`notify-action.sh` today ignores the reason, executes action passed to `--close-action` if any and exits. To my understanding of the spec notification daemon should not emit CloseNotification if notification was archived but not really closed.

But let's first see if this theory is true

**Comment by bkw777** [comment]
Thanks for these pointers. I'm looking in to it now.

**Comment by bkw777** [comment]
Yes I get exactly that message, except the final uint32 value is different for timeouts-to-history vs manual closes.

And I think I see now a little better what's going on, and how most of the behavior I'm seeing is probably down to quirks particular to lxqt-notificationd, and the settings I happen to have set in it.

I did notice one thing different about manual close vs timeout. I rigged up a repeating job in a short loop and captured the messages from 4 types of events:

1 - manually close before timeout
the final uint32 is always 2
these do not get added to history, so that's all there is to these

2 - close by timeout
the final uint32 is always 1
these get added to history and **may or may not** generate another message later

3 - reopen from history, and manually close
the final uint32 is always 2
these are removed from history, so that's all there is for these

4 - clear history without reopening
no dbus event generated
(an event was generated when those notifications were added to history, but no even is generated when the history is cleared without touching any of the individual saved items)

So it seems I can count on that final uint32 to reflect that a notification was manually closed, regardless if it was before the timeout or after pulling back up from history.

Not sure if I can actually DO anything useful with that yet but, it's not too important because along the way I discovered a few other things that suggest that a lot of details about what notifications do is down to quirks of the particular desktop and whatever app it has for displaying them, and whatever settings and features that app has, and whatever settings the user happened to set.

In my case, in lxqt-notificationd, one thing is there is a "default duration" value in seconds, which, when set to 0, the notifications never close themselves, you have to manually close each one. I bet this was even probably the default way back at install.

Also, if I use notify-send.sh -t 0, it has the same effect, that one notification is not expired even if the default is set to say, 3, and other notifications are expiring in 3 seconds. I don't know if I can build that "-t 0" into my app though. Do other desktops treat "-t 0" the same way? Don't worry I'm not asking you to find that out for me, just reminding what my goal is here, it's more about using notify-send.sh within an app that other people use, not so much about me getting my personal desktop doing what I want.

And there is another option which says "ignore these applications"
If I put "foo" into that setting, and then use "notify-send.sh -a foo"
then that particular notification never goes into history. It's either open or gone.

Combining "-t 0" with that "ignore these" setting gives me personally a good all around behavior. I can still have the general default set to timout most notifications the way I wanted it. Notifications from this one app will not timeout. Notifications from this one app will never appear in the history.
And so a non-working button never exists. Either a notification is visible because it has never been closed, and it's button works, or it's totally gone. I als found that repeated notifications from the same app with the same title and body do not generate duplicates on the desktop, so I don't have to go to any special lengths to try to detect and avoid that.

A lot of the details there seem like they must be pretty specific to this particular "lxqt-notificationd" and any other user will have their bag of quirks to figure out. So I probably just don't have to worry about it too much.

Probably the main thing I have to find out is if it's reasonable to build it in to my app to use "-t 0" or will some desktops ignore that as invalid, or close the notification too fast to even see it, or ??

So, all in all, unless you think something can be done with that final uint32 value from the dbus event messages, I think there is nothing for you to fix or improve here.

Anyway, thank you very much for writing this because it's given me a slick enhancement to this app I'm maintaining.

<pre>
closed manually before expiring
/org/freedesktop/Notifications: org.freedesktop.Notifications.NotificationClosed (uint32 137, uint32 2)

expired and moved to history
/org/freedesktop/Notifications: org.freedesktop.Notifications.NotificationClosed (uint32 138, uint32 1)

pulled out of history and then manually closed
/org/freedesktop/Notifications: org.freedesktop.Notifications.NotificationClosed (uint32 141, uint32 2)
</pre>

**Comment by bkw777** [comment]
Even if I hacked notify-action.sh to look at that final uint32 value, I don't think it can be used, because, that particular notification may not ever generate the "closed manually" event. I don't think I want them just piling up in the background. The setting in the app which sets how often it checks for new kernel versions, the minimum interval is 1 hour. So for a desktop at an actual desk that may go months without rebooting, that's a lot of hours.

I would have to hack things up even more to make it so that each time it's called, it checks if another instance is already running or something. I guess I could do that now that I think about it, but I also think I probably don't have to bother. Thanks again.

**Comment by bkw777** [comment]
...and nice, the mystery about "-t 0" is answered, the specification says 0 means never expires. so if anyone's desktop doesn't behave that way, it's not my problem.

**Comment by vlevit** [comment]
As you figured it out the behavior largely depends on notification daemon.

Some differences with GNOME's notification daemon: 

1) it ignores timeout
   The spec says
   >  The timeout time in milliseconds since the display of the notification at which the notification
   **should** automatically close. 

    "should" makes honoring this option by notification daemon optional. If spec said "must" it would have been a spec violation.

2) NotificationClosed signal is not sent on move-to-history  (move-to-history in GNOME I think is pure UI thing: it doesn't emit signals, neither controlled via dbus)

3) NotificationClosed is always sent if notification is actually closed
Even if all messages are cleared from the history for each notification NotificationClosed is sent.
No events are sent after notification is closed. 

`notify-send.sh` relies on that each notification (with actions) receives one NotificationClosed signal to do cleanup and stop the notify-action.sh process.
If lxqt-notificationd might (or might not) send ActionInvoked after NotificationClosed `notify-send.sh` probably won't have reliable event under which it can do the notification's cleanup.
