### ISSUE TITLE
notification position under void/xfce

### ISSUE THREAD

**Issue by BUFU1610** [vlevit/notify-send.sh#14]
Hey there!
I used your brilliant code to script a simple volume notification under xfce and void linux.
The issue that I have is that the notifications will not appear in the position specified under Settings Manager > Notifications. No matter what I do, the notification appears in the upper right corner.
Any hint to what I'm doing wrong or what I can do to change the position another way somehow?
(I cannot use the -h int:x/y:value hint, because xfce-notifyd does not understand these.)

Any help would be appreciated! Thanks!

**Comment by vlevit** [comment]
Hi! If you create notification with `notify-send` (from libnotify) does it appear in the right position?

**Comment by BUFU1610** [comment]
Hello again.
Now that I have tested this again, it just works.
I have installed/uninstalled and reinstalled a bit in the last week, I guess something that blocked this from happening got solved on the way.... hmmm...
So, I will close this and thank you for your response.
