### ISSUE TITLE
Permission issues and other fun stuff.

### ISSUE THREAD

**Issue by Tenemir** [vlevit/notify-send.sh#5]
Running on Linux Mint 18 "Sarah" (which is based on Ubuntu 16.04)
on 64 bit architecture.

After getting past the permission errors with (sudo sh), there are some additional problems:

(The script was run from the home folder).

```
sudo sh ./notify-send.sh --print-id Subject Message
./notify-send.sh: 23: ./notify-send.sh: Syntax error: "(" unexpected
```

I checked line 23 and this is what is in there:

`NOTIFY_ARGS=(--session`

It would be very nice of you to investigate this. Thank you. I really need that "re-draw" ish feature, as killing dunst every time I want to update causes uneccesary flickering due to the delay of restarting dunst (and I assume any other notification server).

**Comment by Tenemir** [comment]
Workaround: use bash instead of sh. Apparently using sh means that it won't respect certain features within the script. 

so:   sudo sh ./notify-send.sh --print-id Subject Message

Thanks for reading.

**Comment by vlevit** [comment]
@Tenemir You can omit `sh` and `bash`, just run `./notify-send.sh` and the script should be interpreted by bash.
