### ISSUE TITLE
Doesn't seem to working out for me.

### ISSUE THREAD

**Issue by DrDonkey** [vlevit/notify-send.sh#9]
I am using Manjaro with i3-gaps wm. I tried all combos but didn't work.
I am using fish if it matters.
I tried it in bash also, but same thing.
I have glib2 installed too.
Also it takes about 50 seconds to run the command then nothing happens.
Is there logging functionality? I can't find it.

**Comment by vlevit** [comment]
@DrDonkey Does original notify-send work for you?

To debug you can try adding `set -x` after shebang to notify-send.sh. I.e.

```bash
#!/usr/bin/env bash
set -x
# notify-send.sh - drop-in replacement for notify-send with more features
...
```
and share the output.

**Comment by DrDonkey** [comment]
@vlevit Please update the readme so that it specifies clearly that it needs a notification server like dunst in background running.

**Comment by vlevit** [comment]
Thanks, I will.
